/**
* @author Matias Menafra 1/6/2010
*/
public class DAOActivity {
	
	/**
	* Constructor
	*/
	public DAOActivity(){
	
	}
	
	/**
	* 
	*/
	public void logProjectActivity(String projectId, DateTime timeStamp, String modifiedBy, String action, String name, String access){
		
	}
	
	/**
	* 
	*/
	public void logMemberActivity(String projectId, DateTime timeStamp, String modifiedBy, String action){
		
	}
	
	/**
	* 
	*/
	public void logTaskCommentActivity(String projectId, DateTime timeStamp, String modifiedBy, String action){
		
	}
	
	/**
	* 
	*/
	public void logTaskAssigneeActivity(String projectId, DateTime timeStamp, String modifiedBy, String action){
		
	}
	
	/**
	* 
	*/
	public void logTaskActivity(String projectId, DateTime timeStamp, String modifiedBy, String action){
		
	}
	
	/**
	* 
	*/
	public void logAttachmentActivity(String projectId, DateTime timeStamp, String modifiedBy, String action){
		
	}

	/**
	* 
	*/
	public void listBy(){
	
	}
}