/**
*@author Matias Menafra @ 12/17/2009
*/
public class Project {

	public String 	access 			{ set; get; }
	public Boolean 	allowCPU 		{ set; get; }
	public Boolean 	allowPPU 		{ set; get; }
	public String 	daysWorkWeek 	{ set; get; }
	public String 	description 	{ set; get; }
	public String 	displayDuration { set; get; }
	public String 	image 			{ set; get; }
	public String 	picture 		{ set; get; }
	public String 	priority 		{ set; get; }
	public String 	createdBy 		{ set; get; }
	public Date 	createdDate 	{ set; get; }
	public String 	prjType 		{ set; get; }
	public Integer 	workingHours 	{ set; get; }
	
	/**
	* Constructor
	*/
	public Project(){
	
	}
}