/**
*@author Matias Menafra @ 12/18/2009
*/
public class TaskPredecessor {

	public Integer 	lagTime 		{ set; get; }
	public String 	lagType 		{ set; get; }
	public String 	lagUnit 		{ set; get; }
	public String 	parent 			{ set; get; }
	public String 	predecessor 	{ set; get; }
	public String 	project 		{ set; get; }
	public String 	createdBy 		{ set; get; }
	
	/**
	* Constructor
	*/
	public TaskPredecessor(){
	
	}
}